Update programmingKnowledge_tutorial_44_video

diff --git a/programmingKnowledge_tutorial_44_video b/programmingKnowledge_tutorial_44_video
--- a/programmingKnowledge_tutorial_44_video
+++ b/programmingKnowledge_tutorial_44_video
@@ -869,8 +869,29 @@ echo "the name is $name : Before"
 print max
 echo "the name is $name : After"
 ---------------------------Shell Scripting Tutorial for Beginners 25 - Function Example-----------------
-n this video we will create an example. This example shell script will demonstrate the concept of Bash shell functions. we will show to check if a file exists or not using function.
+this video we will create an example. This example shell script will demonstrate the concept of Bash shell functions. we will show to check if a file exists or not using function.
+#!/bin/bash
+usage() {
+echo "you need to provide an argument : "
+echo "usage : $0 file_name"
+}
 
+is_file_exist() {
+  local file="$1"
+  [[ -f "$file" ]] && return 0 || return 1
+}
+
+[[ $# -eq 0 ]] && usage
+
+if ( is_file_exist "$1" )
+then
+   echo "file found"
+else
+   echo "file not found"
+fi
+----------------------------Shell Scripting Tutorial for Beginners 26 - Readonly command-----------------
+readonly command can be used to to make you variables and functions read only that means you cannot change the value of variables or you can not overwrite a function.
+#!/bin/bash
 
 
 
